### ISSUE TITLE
"Permission denied" error on docker run

### ISSUE THREAD

**Issue by hacksdump** [programming-liftoff/docker-playground#3]
I am currently using Ubuntu 18.04.
`docker build -t playground:latest .` completed successfully but 
`docker run -it -rm playground` failed with error:

> standard_init_linux.go:190: exec user process caused "permission denied"

But a small change in `Dockerfile` solved my issue, which was:
`RUN chmod 744 /entry_point.sh`
replaced with
`RUN ["chmod", "+x", "/entry_point.sh"]`

Should I create a fork and add a pull request for this change?

**Comment by BetaUliansyah** [comment]
> I am currently using Ubuntu 18.04.
> `docker build -t playground:latest .` completed successfully but
> `docker run -it -rm playground` failed with error:
> 
> > standard_init_linux.go:190: exec user process caused "permission denied"
> 
> But a small change in `Dockerfile` solved my issue, which was:
> `RUN chmod 744 /entry_point.sh`
> replaced with
> `RUN ["chmod", "+x", "/entry_point.sh"]`
> 
> Should I create a fork and add a pull request for this change?

Yes, you should.

**Comment by programming-liftoff** [comment]
Just merged this PR, thanks!
